### PR TITLE
switch from `babel-eslint` to non-deprecated `@babel/eslint-parser`

### PR DESCRIPTION
**Pull request by brettz9**
chore: switch from `babel-eslint` to non-deprecated `@babel/eslint-parser`

### CODE REVIEW

**Comment by gajus** [comment]
What's the reason for having that empty json file?

**Comment by brettz9** [comment]
The new parser says:

> @babel/eslint-parser requires @babel/core@>=7.2.0 and a valid Babel configuration file to run.

...and when I try performing `eslint` against your code base (via `$(npm bin)/eslint . --config=eslintrc.js`), I see errors without it. As it seems you aren't dogfooding it, I can remove the file, but I did it in case you want to catch errors in this repo. There are a couple errors now if applying that config file against the code base, though most (though not all) relate to canonical expecting non-modules (so adding linting would require another config to override those details).

**Comment by gajus** [comment]
Thank you

**Pull request merged**
