### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by laggingreflex**
A bug was recently fixed in https://github.com/jacobrask/eslint-plugin-sorting/pull/15

### CODE REVIEW

**Comment by gajus** [comment]
@laggingreflex Is there a particular use case for wanting this to be committed to the source control?

> "eslint-plugin-sorting": "^0.1.0"
> "eslint": "^2.11.1",

This version range matches your proposed changes. In general, package.json dependencies need to be bumped only in case of major version change or if package.json defines `bundledDependencies` property.

**Comment by laggingreflex** [comment]
Ah never mind. I don't know why I thought this applied to only patch semver.

**Comment by laggingreflex** [comment]
I was still having the issue that eslint-plugin-sorting wasn't being installed to the latest version.

It seems that what you said only applies when the major version is >1 (and conversely what I believed only applies when it's <1)

https://docs.npmjs.com/misc/semver#caret-ranges

>     ^1.2.3 := >=1.2.3 <2.0.0
>     ^0.2.3 := >=0.2.3 <0.3.0
>     ^0.0.3 := >=0.0.3 <0.0.4

**Comment by gajus** [comment]
> It seems that what you said only applies when the major version is >1 (and what I thought only applies when it's <1)

It seems that you are right. Did not know that:

> this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

Thank you

**Comment by gajus** [comment]
New version pushed

**Pull request merged**
