### PR TITLE
Resolves #72 switch from eslint-plugin-node to eslint-plugin-n

### LINKED ISSUE #72: eslint-plugin-node seems to be deprecated or not maintained
I think the node config should use https://www.npmjs.com/package/eslint-plugin-n instead of https://www.npmjs.com/package/eslint-plugin-node to be up to date

### PR DESCRIPTION
**Pull request by beuluis**
Resolves #72
Replace eslint-plugin-node with eslint-plugin-n as the old one is not maintained anymore: https://github.com/mysticatea/eslint-plugin-node/issues/300

### CODE REVIEW

**Comment by beuluis** [comment]
Hey there @gajus,

did you have time to take a look?

Should i provide it via a different process?

Let me know what i can do to get this merged🙂

Thanks!

**Comment by beuluis** [comment]
Sorry @gajus my bad. Fixed the misconfigured npmrc on my side :)

**Comment by beuluis** [comment]
@gajus I fixed all i could find. But I noticed that the `find-deprecated` script is broken due to a usage of the ES Module `got`.

Investigated but this was already introduced 8 months ago. So i did not touch it to separate it from those changes here.

**Comment by gajus** [comment]
Thank you!

**Pull request merged**
